const songs = [
  {
    number: 1,
    title: 'Baptized In Fear',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I fell asleep in the tub, I was there with paralysis',
          'My foot hit the faucet, water started flowing in',
          "Couldn't scream for help, I just slowly felt the pressure hit",
          'Moving one toe was the only form of motion left',
          "Can't breathe for air, can't breathe",
          'Trying to remember everything that my preacher said',
          'Tryna right my wrongs, my regrets filling up my head',
          "All the times I dodged death, this can't be the way it ends, no",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Figure in the corner I can't quite see",
          "I just know the shadow's staring at me",
          'It gets closer, it gets closer, it gets closer now',
          'Figure in the corner laughing at me',
          'Water fill my lungs, vision blurry',
          'Heartbeat slower, heartbeat slower, heartbeat slower',
        ],
      },
      {
        label: '-xo-',
        lines: ["Voices'll tell me that I should carry on"],
      },
    ],
  },
  {
    number: 2,
    title: 'Open Hearts',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I can hear the wind blow, even through the window',
          'I can hear the whisper, even with my ears closed',
          'All the silver and gold only made my skin cold',
          'I told myself I would never get old then you pulled me in close',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Falling, angels call my name',
          'But the things you say',
          'keeps me alive again',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Where do I start',
          'when I open my heart',
          "It's never easy falling in love again",
          'Cover my scars',
          'when I open my arms',
          "It's never easy falling in love again",
          'Falling in, falling in love',
          "It's never easy falling in love again",
          'Falling in, falling in love',
          'Falling in love again',
        ],
      },
    ],
  },
  {
    number: 3,
    title: 'Wake Me Up',
    sections: [
      {
        label: '-xo-',
        lines: [
          'All I have is my legacy',
          'I been losing my memory',
          'No afterlife, no other side',
          "I'm all alone when it fades to black",
          'Fades to black',
          'No afterlife, no other side',
          "I'm all alone when it fades to black",
          'Play smile, live fully',
          'When life is hard',
          "I know death's easy",
          'Woah',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Sun is never rising',
          "I don't know if it's day or night",
          "And I can't find the horizon",
          "I'm running out of time",
          'Are you real, or are you an illusion',
          "'Cause I fear your love's my delusion",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Wake me up, come find me',
          "It feels like I'm dying",
          'Wake me up, these demons',
          "keep creeping, don't fear 'em",
          "Wake me up, 'cause I'm trying",
          'This sleep is paralyzing',
          "Wake me up, 'cause I'm dreaming",
          'It feels so damn real',
          'Wake me up',
        ],
      },
    ],
  },
  {
    number: 4,
    title: 'After Hours',
    sections: [
      {
        label: '-xo-',
        lines: [
          'My darkest hours',
          'Girl, I felt so alone inside of this crowded room',
          "Different girls on the floor, distractin' my thoughts of you",
          'I turned into the man I used to be, to be',
          'Put myself to sleep',
          'Just so I can get closer to you inside my dreams',
          "Didn't wanna wake up 'less you were beside me",
          'I just wanted to call you and say, and say',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Oh, baby',
          'Where are you now when I need you most',
          "I'd give it all just to hold you close",
          'Sorry that I broke your heart, your heart',
          'I said, baby',
          "I'll treat you better than I did before",
          "I'll hold you down and not let you go",
          "This time, I won't break your heart, your heart, yeah",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I know it's all my fault",
          'Made you put down your guard',
          'I know I made you fall',
          'Then said you were wrong for me',
          'I lied to you, I lied to you, I lied to you',
          "Can't hide the truth, I stayed with her in spite of you",
          'You did some things that you regret, still right for you',
          "'Cause this house is not a home",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Without my baby',
          'Where are you now when I need you most',
          'I gave it all just to hold you close',
          'Sorry that I broke your heart, your heart',
          'And I said, baby',
          "I'll treat you better than I did before",
          "I'll hold you down and not let you go",
          "This time, I won't break your heart, your heart, no",
        ],
      },
    ],
  },
  {
    number: 5,
    title: 'Starboy',
    sections: [
      {
        label: '-xo-',
        lines: [
          "I'm tryna put you in the worst mood, ah",
          'P1 cleaner than your church shoes, ah',
          'Milli point two just to hurt you, ah',
          "All red Lamb' just to tease you, ah",
          'None of these toys on lease too, ah',
          'Made your whole year in a week too, yah',
          'Main bitch outta your league too, ah',
          'Side bitch outta your league too, ah',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'House so empty, need a centerpiece',
          'Twenty racks a table, cut from ebony',
          'Cut that ivory into skinny pieces',
          'Then she clean it with her face, man, I love my baby, ah',
          "You talkin' money, need a hearin' aid",
          "You talkin' 'bout me, I don't see the shade",
          'Switch up my style, I take any lane',
          'I switch up my cup, I kill any pain',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "Look what you've done",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "I'm a motherfuckin' starboy",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "Look what you've done",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "I'm a motherfuckin' starboy",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Let a nigga brag Pitt',
          'Legend of the fall, took the year like a bandit',
          'Bought Mama a crib and a brand new wagon',
          "Now she hit the grocery shop lookin' lavish",
          'Star Trek roof in that Wraith of Khan',
          'Girls get loose when they hear this song',
          'A hundred on the dash get me close to God',
          "We don't pray for love, we just pray for cars",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'House so empty, need a centerpiece',
          'Twenty racks a table, cut from ebony',
          'Cut that ivory into skinny pieces',
          'Then she clean it with her face, man, I love my baby, ah',
          "You talkin' money, need a hearin' aid",
          "You talkin' 'bout me, I don't see the shade",
          'Switch up my style, I take any lane',
          'I switch up my cup, I kill any pain',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "Look what you've done",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "I'm a motherfuckin' starboy",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "Look what you've done",
          'Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha',
          "I'm a motherfuckin' starboy",
        ],
      },
    ],
  },
  {
    number: 6,
    title: 'Heartless',
    sections: [
      {
        label: '-xo-',
        lines: [
          "Never need a bitch, I'm what a bitch needs",
          'Tryna find the one that can fix me',
          "I've been dodging death in the six speed",
          'Amphetamine got my stummy feeling sickly',
          'Yeah, I want it all now',
          "I've been running through the pussy, need a dog pound",
          'Hundred models getting faded in the compound',
          'Tryna love me but they never get a pulse down',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "'Cause I'm heartless",
          "And I'm back to my ways 'cause I'm heartless",
          'All this money and this pain got me heartless',
          "Low life for life 'cause I'm heartless",
          "Said I'm heartless",
          "Tryna be a better man but I'm heartless",
          'Never be a wedding plan for the heartless',
          "Low life for life 'cause I'm heartless",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Said I'm heartless",
          'So much pussy it be falling out the pocket',
          'Metro Boomin turn this hoe into a moshpit',
          'Tesla pill got me flying like a cockpit',
          'Yeah, I got her watching',
          'Call me up turn that pussy to a faucet',
          'Duffel bags full of drugs and rocket',
          'Stix drunk but he never miss a target',
          "Photoshoots I'm a star now",
          "I'm talking Time, Rolling Stone and Bazaar now",
          "Sellin' dreams to these girls with their guard down",
          "Seven years I've been swimming with the sharks now",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "'Cause I'm heartless",
          "And I'm back to my ways 'cause I'm heartless",
          'All this money and this pain got me heartless',
          "Low life for life 'cause I'm heartless",
          "Said I'm heartless",
          "Tryna be a better man but I'm heartless",
          'Never be a wedding plan for the heartless',
          "Low life for life 'cause I'm heartless",
        ],
      },
    ],
  },
  {
    number: 7,
    title: 'Cry For Me',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I can feel it',
          "Girl, pick up your phone, I can't believe it",
          'I can feel my spirit slowly leaving',
          "I can't see myself and I'm not breathing",
          "I'm not breathing",
          'Slowly bleeding',
          'I wish that I told you all my feelings',
          'I hope that I live life for a reason',
          "But at least you'll play this song when I'm gone",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'And I hope you cry for me like I cry for you',
          'Every night for you, take it easy on me, baby',
          "'Cause I tried with you, saw my life with you",
          "End of time with you, now we're strangers",
          'And I hope that you still cry for me like I cry for you',
          "Every night for you, I've been living with this lie",
          "Now I can't hide the truth, I can't hide the truth",
          "Girl, I'll cry for you",
          "Girl, I'll cry for you, ooh, yeah",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't see clear",
          'I wash my fears with whisky tears',
          'I disappear',
          "Don't interfere, the end is near",
          "The crowd'll scream",
          'I block my ears to stop the cheers',
          "'Cause the stage took a toll",
          'Been faded on the floor',
          "In this penthouse prison, I'm alone",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'And I hope you cry for me like I cry for you',
          'Every night for you, take it easy on me, baby',
          "'Cause I tried with you, saw my life with you",
          "End of time with you, now we're strangers",
          'And I hope that you still cry for me like I cry for you',
          "Every night for you, I've been living with this lie",
          "Now I can't hide the truth, I can't hide the truth",
          "Girl, I'll cry for you",
          "Girl, I'll cry for you, ooh, yeah",
        ],
      },
    ],
  },
  {
    number: 8,
    title: 'Sao Paulo',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Baby, ride me to the darkness of the night',
          'Kill me softly like you want me euthanized, oh yeah',
          "Hot like risin'sun, burnin' evrything she touch",
          'She dont even want your money, can buy you and someone else',
          'She addicted to the rush, I can never get enough',
          'She desensitized to money, need to play with someone else',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Baby, you turn me on',
          'Baby, you turn me on',
          'Baby, you turn me on',
          'Hit it from the back, she louder than two sold out nights',
          'I think she fell in love, she said she trust me with her life',
          "Hot like risin'sun, burnin' evrything she touch",
          'She dont even want your money, can buy you and someone else',
          'She addicted to the rush, I can never get enough',
          'She desensitized to money, need to play with someone else',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Baby, you turn me on',
          'I love it when your turn me on',
          'See how you turn me on',
          'I love it when your turn me on',
          'Oh, baby',
          'Oh, oh',
          'Oh, oh',
          'Take it easy, easy on me',
        ],
      },
    ],
  },
  {
    number: 9,
    title: 'Take My Breath',
    sections: [
      {
        label: '-xo-',
        lines: [
          "It's like a dream what she feels with me",
          'She loves to be on the edge',
          'Her fantasy is okay with me',
          'Then suddenly, baby says',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I saw the fire in your eyes',
          'I saw the fire when I looked into your eyes',
          'You tell me things you wanna try',
          'I know temptation is the devil in disguise',
          'You risk it all to feel alive, oh yeah',
          "You're offering yourself to me like sacrifice",
          'You said you did this all the time',
          'Tell me you love me if I bring you to the light',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "It's like a dream what she feels with me",
          'She loves to be on the edge',
          'Her fantasy is okay with me',
          'Then suddenly, baby says',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Take my breath away',
          'And make it last forever, babe',
          'Do it now or never, babe (Ah)',
          'Take my breath away',
          'Nobody does it better, babe',
          'Bring me close to',
        ],
      },
      {
        label: '-xo-',
        lines: ["Oh, oh-oh-ooh, they'll see me", 'Oh-ooh, ooh-oh no'],
      },
      {
        label: '-xo-',
        lines: [
          'Take my breath away',
          'And make it last forever, babe',
          'Do it now or never, babe',
          'Take my breath away',
          'Nobody does it better, babe',
          'Bring me close to heaven, babe',
          'Take my breath',
        ],
      },
    ],
  },
  {
    number: 10,
    title: 'Sacrifice',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I was born in a city',
          "Where the winter nights don't ever sleep",
          "So this life's always with me",
          'The ice inside my veins will never bleed',
          'My, ooh',
          'My, ooh',
          'Every time you try to fix me',
          "I know you'll never find that missing piece",
          'When you cry and say you miss me',
          "I lie and tell you that I'll never leave",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'But I sacrifice',
          'Your love for more of the night',
          'I try to put up a fight',
          "Can't tie me down",
          "I don't want to sacrifice",
          'For your love, I try',
          "I don't want to sacrifice",
          'But I love my time',
        ],
      },
    ],
  },
  {
    number: 11,
    title: 'How Do I Make You Love Me',
    sections: [
      {
        label: '-xo-',
        lines: [
          "We're going back in time",
          "I'd like to see you try",
          'Unpacking thoughts through tunnels in your mind',
          "I'll fix you mushroom tea",
          'And cross the restless sea',
          'Release yourself to escape reality',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "It doesn't phase you",
          'I need a breakthrough',
          "I only want what's right in front of me",
          "It's quite unusual",
          'Seeking approval',
          'Begging for it desperately',
          'I said',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'How do I make you love me',
          'How do I make you fall for me',
          'How do I make you want me',
          'And make it last eternally',
          'How do I make you love me (Ooh ahh)',
          'How do I make you fall for me',
          'How do I make you want me (Ooh ahh)',
          'And make it last eternally',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I can see the real you, girl',
          "You don't have to hide",
          "Forget 'bout what your daddy said",
          "I'll teach you how to shine",
          'And all the things you tolerated made you cold inside',
          'But I can light you up again like embers of a fire',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "It doesn't faze you",
          'I need a breakthrough',
          "I only want what's right in front of me",
          'Its quite unusual',
          'Seeking approval',
          'Begging for it desperately',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'How do I make you love me',
          'How do I make you fall for me',
          'How do I make you want me',
          'And make it last eternally',
          'How do I make you love me (Ooh ahh)',
          'How do I make you fall for me',
          'How do I make you want me (Ooh ahh)',
          'And make it last eternally',
        ],
      },
    ],
  },
  {
    number: 12,
    title: "Can't Feel My Face",
    sections: [
      {
        label: '-xo-',
        lines: [
          "And I know she'll be the death of me",
          "At least we'll both be numb",
          "And she'll always get the best of me",
          'The worst is yet to come',
          "But at least we'll both be beautiful and stay forever young",
          'This I know, (yeah) this I know',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'She told me, "Don\'t worry about it"',
          'She told me, "Don\'t worry no more"',
          "We both knew we can't go without it",
          'She told me, "You\'ll never be alone"',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't feel my face when I'm with you",
          'But I love it, but I love it, oh',
          "I can't feel my face when I'm with you",
          'But I love it, but I love it, oh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "And I know she'll be the death of me",
          "At least we'll both be numb",
          "And she'll always get the best of me",
          'The worst is yet to come',
          "All the misery was necessary when we're deep in love",
          'Yes, I know (yes, I know), girl, I know',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'She told me, "Don\'t worry about it"',
          'She told me, "Don\'t worry no more"',
          "We both knew we can't go without it",
          'She told me, "You\'ll never be alone"',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't feel my face when I'm with you",
          'But I love it, but I love it, oh',
          "I can't feel my face when I'm with you",
          'But I love it, but I love it, oh',
        ],
      },
    ],
  },
  {
    number: 13,
    title: 'Lost In The Fire',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I wanna fuck you slow with the lights on',
          "You're the only one I got my sights on",
          'Type of sex you could never put a price on',
          "I'll take it off, you're the one I'll roll the dice on",
          'And I just want a baby with the right one',
          "'Cause I could never be the one to hide one",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'And we lost a lot of things in the fire',
          'So it took a year for me to find out',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Oh-oh)',
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Yeah)',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'm tired of being home alone",
          'Used to have a girl a day',
          'But I want you to stay',
          'You said you might be into girls',
          "Said you're going through a phase",
          'Keeping your heart safe',
          'Well, baby, you can bring a friend',
          'She can ride on top your face',
          'While I fuck you straight',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'And we lost a lot of things in the fire',
          'So it took a year for me to find out',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Oh-oh, oh-oh)',
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Whoa-oh)',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'm tired of being home alone",
          'Used to have a girl a day',
          'But I want you to stay',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Oh-oh, oh-oh, oh-oh, oh-oh)',
          'Ooh, ooh-ooh-ooh (Oh-oh, oh-oh, oh-oh)',
          "I can't lose you, babe",
          "I can't lose you, babe",
          "I can't lose you, babe",
          'Oh-oh (Oh-oh, oh-oh, oh-oh, oh-oh)',
          'Ooh-ooh',
        ],
      },
    ],
  },
  {
    number: 14,
    title: 'Often',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I usually love sleeping all alone',
          'This time around bring your friend with you',
          "But we ain't really going to sleep at all",
          "You ain't gonna catch me with them sneak pictures",
          "In my city I'm a young God",
          'That pussy kill be so vicious',
          'My God white, he in my pocket',
          "He get me redder than the devil 'til I go nauseous",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'She asked me if I do this every day, I said, "Often"',
          'Asked how many times she rode the wave, not so often (baby)',
          'Bitches down to do it either way, often',
          'Baby, I can make that pussy rain, often',
          'Often, often, girl, I do this often',
          "Make that pussy poppin', do it how I want it",
          'Often, often, girl, I do this often',
          "Make that pussy poppin', do it how I want it",
          'Often',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Oh, the sun's risin' up",
          "The night's almost up",
          "The night's almost done",
          'But I see your eyes',
          'You wanna go again',
          "Girl, I'll go again",
          'She asked me if I do this every day, I said, "Often"',
          'Asked how many times she rode the wave, not so often (baby)',
          'Bitches down to do it either way, often',
          'Baby, I can make that pussy rain, often',
          'Often, often, girl, I do this often',
          "Make that pussy poppin', do it how I want it",
          'Often, often, girl, I do this often',
          "Make that pussy poppin', do it how I want it",
          'Often',
        ],
      },
    ],
  },
  {
    number: 15,
    title: 'Given Up On Me',
    sections: [
      {
        label: '-xo-',
        lines: [
          "I've been lying to your faces, yeah",
          "I've been always wasted, it's too late to save me",
          'Save me, save me, save me',
          'Oh, save me',
          'Fill another cup of forsaken',
          "Yeah, 'til my stomach achin', bloated in my face, and",
          'Face it, face it, face it',
          'Just let me go',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'll always lie to you",
          "I'm unreliable",
          'Tell me you care for me',
          'Just give me what I need, eh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Why won't you let me go",
          "Why won't you let me leave",
          'I give it up on me, yeah',
          "I think I'm in too deep",
          "Why won't you let me go Oh-oh",
          "Why won't you let me leave (Yeah)",
          'I give it up on me, yeah',
          "I think I'm in too deep",
        ],
      },
    ],
  },
  {
    number: 16,
    title: 'I Was Never There',
    sections: [
      {
        label: '-xo-',
        lines: [
          'What makes a grown man wanna cry',
          'What makes him wanna take his life',
          'His happiness is never real',
          'And mindless sex is how he feels, ooh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "When it's time, when it's time, when it's time",
          "It won't matter",
          "When it's time, when it's time, when it's time",
          "It won't matter, it won't matter",
          'It was like I was never there',
          'It was like he was gone in thin air, oh',
          "When it's time, when it's time, when it's time",
          "It won't matter, it won't matter",
        ],
      },
    ],
  },
  {
    number: 17,
    title: 'The Hills',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Your man on the road, he doing promo',
          'You said keep our business on the low-low',
          "I'm just tryna get you out the friend zone",
          'Cause you look even better than the photos',
          "I can't find your house, send me the info",
          'Driving through the gated residential',
          'Found out I was coming, sent your friends home',
          'Keep on tryna hide it but your friends know',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I only call you when it's half past five",
          "The only time that I'll be by your side",
          'I only love it when you touch me, not feel me',
          "When I'm fucked up, that's the real me",
          "When I'm fucked up, that's the real me, yeah",
          "I only call you when it's half past five",
          "The only time I'd ever call you mine",
          'I only love it when you touch me, not feel me',
          "When I'm fucked up, that's the real me",
          "When I'm fucked up, that's the real me, babe",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Hills have eyes, the hills have eyes',
          'Who are you to judge, who are you to judge',
          'Hide your lies, girl, hide your lies',
          'Only you to trust, only you',
          "I only call you when it's half past five",
          "The only time that I'll be by your side",
          'I only love it when you touch me, not feel me',
          "When I'm fucked up, that's the real me",
          "When I'm fucked up, that's the real me, yeah",
          "I only call you when it's half past five",
          "The only time I'd ever call you mine",
          'I only love it when you touch me, not feel me',
          "When I'm fucked up, that's the real me",
          "When I'm fucked up, that's the real me, babe",
        ],
      },
    ],
  },
  {
    number: 18,
    title: 'Timeless',
    sections: [
      {
        label: '-xo-',
        lines: [
          "Oh, city on fire when I'm comin' home",
          'Fill up the sky, I fill up the Dome',
          "They'll play it one day, it's a hell of a show",
          "But it's gonna hurt 'cause we did it first",
          'Feel like Skateboard P, BBC boys on the creep',
          "Feel like it's '03, Neptune drum with a beam",
          "She hippie-flippin' a bean, she wanna fuck with the team",
          'She fell in love with the cream, she fell in love with the scene',
          'Ooh, yeah, her man quiet, not a peep',
          'Broke his heart, PTSD',
          'Hold his chest, let it breathe',
          'Let it breathe, niggas scheme',
          'And I got a priest, he got a cross',
          'Get out of line, send him to God',
          'I shed a tear, pray for a loss, ooh, yeah',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Ever since I was a kid, I been legit',
          'If I was you, I would cut up my wrist',
          'XO tatted all over her body, yeah',
          "She just wanna roll and I don't mind it, yeah",
          'Ever since I was jit, I been legit',
          'You should let her go, she wanna be it',
          'Double-O tatted on her body, yeah',
          "It don't matter what they say, I'm timeless, yeah",
        ],
      },
    ],
  },
  {
    number: 19,
    title: 'Kiss Land',
    sections: [
      {
        label: '-xo-',
        lines: [
          "This ain't nothing to relate to",
          "And this ain't nothing to relate to",
          "And this ain't nothing to relate to",
          "This ain't nothing to relate to",
          'Even if you tried, you tried, you tried',
          'You tried, you tried, you tried',
          'You tried, you tried, you tried',
          'You tried, you tried, you tried',
        ],
      },
    ],
  },
  {
    number: 20,
    title: "Creepin'",
    sections: [
      {
        label: '-xo-',
        lines: [
          'Somebody said they saw you',
          "The person you were kissing wasn't me",
          'And I would never ask you',
          'I just kept it to myself',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I don't wanna know",
          "If you're playin' me, keep it on the low",
          "'Cause my heart can't take it anymore",
          "And if you're creepin', please, don't let it show",
          "Oh, baby, I don't wanna know",
        ],
      },
    ],
  },
  {
    number: 21,
    title: 'One Of The Girls',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Tell nobody I control you',
          'I broke you just to own you',
          "They can't tell that I love you",
          "'Cause you're loyal, baby",
          "I love when you're submissive",
          'You love it when I break skin',
          "You feel pain without flinchin'",
          'So say it',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Give me tough love',
          "Leave me with nothin' when I come down",
          'My kind of love',
          "Force me and choke me 'til I pass out",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "We don't gotta be in love, no",
          "I don't gotta be the one, no",
          'I just wanna be one of your girls tonight',
          "We don't gotta be in love, no",
          "I don't gotta be the one, no",
          'I just wanna be one of your girls tonight, oh-oh-oh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Give me tough love',
          "Leave me with nothin' when I come down",
          'My kind of love',
          "Force me and choke me 'til I pass out",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "We don't gotta be in love, no",
          "I don't gotta be the one, no",
          'I just wanna be one of your girls tonight (Tonight)',
          "We don't gotta be in love, no",
          "I don't gotta be the one, no (Oh)",
          'I just wanna be one of your girls tonight (Oh), oh-oh-oh',
        ],
      },
    ],
  },
  {
    number: 22,
    title: "Stargirl Interlude",
    sections: [
      {
        label: '-xo-',
        lines: [
          "I had a vision",
          "A vision of my nails in the kitchen",
          "Scratchin' counter tops, I was screamin'",
          "My back arched like a cat",
          "My position couldn't stop, you were hittin'",
          "And I shouldn't cry, but I love it, starboy",
          "And I shouldn't cry, but I love it (I love it), starboy",
          "And I shouldn't cry, but I love it, starboy",
          "And I shouldn't cry, but I love it, starboy",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I just wanna see you shine 'cause I know you're a stargirl",
          "I just wanna see you shine 'cause I know you're a stargirl",
          "I just wanna see you shine 'cause I know you're a stargirl",
          "I just wanna see you shine 'cause I know you're a stargirl"
        ],
      },
    ],
  },
  {
    number: 23,
    title: 'Out Of Time',
    sections: [
      {
        label: '-xo-',
        lines: [
          "The last few months I've been working on me, baby",
          "There's so much trauma in my life",
          "I've been so cold to the ones who loved me, baby",
          'I look back now and I realize',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'And I remember when I held you',
          'You begged me with your drowning eyes to stay',
          "And I regret I didn't tell you",
          "Now I can't keep you from loving him",
          'You made up your mind',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Say I love you, girl, but I'm out of time",
          "Say I'm there for you but I'm out of time",
          "Say that I'll care for you but I'm out of time",
          "Said I'm too late to make you mine, out of time",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'If he mess up just a little',
          'Baby, you know my line',
          "If you don't trust him a little",
          'Then come right back, girl, come right back',
          'Gimme one chance, just a little',
          "Baby, I'll treat you right",
          "And I'll love you like I should've loved you all the time",
        ],
      },
    ],
  },
  {
    number: 24,
    title: 'I Feel It Coming',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Tell me what you really like',
          'Baby I can take my time',
          "We don't ever have to fight",
          'Just take it step-by-step',
          'I can see it in your eyes',
          "'Cause they never tell me lies",
          'I can feel that body shake',
          'And the heat between your legs',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "You've been scared of love and what it did to you",
          "You don't have to run, I know what you've been through",
          'Just a simple touch and it can set you free',
          "We don't have to rush when you're alone with me",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I feel it coming, I feel it coming',
          'I feel it coming, I feel it coming',
          'I feel it coming, I feel it coming',
          'I feel it coming, I feel it coming',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I know what you feel right now',
          'I feel it coming, I feel it coming',
          'I know what you say right now',
          'I feel it coming',
        ],
      },
    ],
  },
  {
    number: 25,
    title: 'Die For You',
    sections: [
      {
        label: '-xo-',
        lines: [
          "I'm findin' ways to articulate",
          "The feeling I'm goin' through",
          "I just can't say I don't love you",
          "'Cause I love you, yeah",
          "It's hard for me to communicate the thoughts that I hold",
          "But tonight I'm gon' let you know",
          'Let me tell the truth',
          'Baby let me tell the truth, yeah',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "You know what I'm thinkin'",
          'See it in your eyes',
          'You hate that you want me',
          'Hate it when you cry',
          "You're scared to be lonely",
          "'Specially in the night",
          "I'm scared that I'll miss you",
          'Happens every time',
          "I don't want this feelin'",
          "I can't afford love",
          'I try to find a reason to pull us apart',
          "It ain't workin' 'cause you're perfect",
          "And I know that you're worth it",
          "I can't walk away, oh!",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Even though we're going through it",
          'If it makes you feel alone',
          'Just know that I would die for you',
          'Baby I would die for you, yeah',
          'The distance and the time between us',
          "It'll never change my mind, 'cause baby",
          'I would die for you',
          'Baby I would die for you, yeah',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I would die for you',
          'I would lie for you',
          'Keep it real with you',
          'I would kill for you, my baby',
          "I'm just sayin', yeah",
          'I would die for you',
          'I would lie for you',
          'Keep it real with you',
          'I would kill for you, my baby',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Even though we're going through it",
          'If it makes you feel alone',
          'Just know that I would die for you',
          'Baby I would die for you, yeah',
          'The distance and the time between us',
          "It'll never change my mind, 'cause baby",
          'I would die for you',
          'Baby I would die for you, yeah',
        ],
      },
    ],
  },
  {
    number: 26,
    title: 'Is There Someone Else',
    sections: [
      {
        label: '-xo-',
        lines: [
          "I know that you're hiding something from me",
          "That's been close to your heart",
          "And I felt it creepin' up everyday",
          'Baby, right from the start',
          "I know that look you give when we're fighting",
          "We're fighting",
          "'Cause I used to be the one who was lying, oh lying",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Oh, is there someone else or not',
          "'Cause I wanna keep you close",
          "I don't wanna lose my spot",
          "'Cause I need to know",
          "If you're hurting him, or you're hurting me",
          "If I ain't with you, I don't wanna be",
          'Is there someone else or not',
          'Ooh, or not',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I don't deserve someone loyal to me",
          "Don't you think I see",
          "And I don't wanna be a prisoner to who I used to be",
          'I swear I changed my ways for the better, the better',
          "'Cause I wanna be with you forever, forever",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Oh, is there someone else or not',
          "'Cause I wanna keep you close",
          "I don't wanna lose my spot",
          "'Cause I need to know",
          "If you're hurting him, or you're hurting me",
          "If I ain't with you, I don't wanna be",
          'Is there someone else or not',
          'Ooh, or not',
        ],
      },
    ],
  },
  {
    number: 27,
    title: 'Wicked Games',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Bring your love, baby, I could bring my shame',
          'Bring the drugs, baby, I could bring my pain',
          'I got my heart right here',
          'I got my scars right here',
          'Bring the cups, baby, I could bring the drink',
          'Bring your body, baby, I could bring you fame',
          "And that's my motherfucking words too",
          'Just let me motherfucking love you',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Listen ma, I'll give you all I got",
          'Get me off of this, I need confidence in myself',
          "Listen ma, I'll give you all of me",
          'Give me all of it, I need all of it to myself',
          'So tell me you love me',
        ],
      },
    ],
  },
  {
    number: 28,
    title: 'Call Out My Name',
    sections: [
      {
        label: '-xo-',
        lines: [
          'We found each other',
          'I helped you out of a broken place',
          'You gave me comfort',
          'But falling for you was my mistake',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I put you on top, I put you on top',
          'I claimed you so proud, and openly',
          'And when times were rough, when times were rough',
          'I made sure I held, you close, to me',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'So call out my name',
          'Call out my name when I kiss you so gently',
          'I want you to stay',
          "I want you to stay even though you don't want me",
          "Girl, why can't you wait",
          "Girl, why can't you wait 'til, I fall out of love",
          "Won't you call out my name",
          "Girl, call out my name, and I'll be on my way",
          "And I'll be on my",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I said I didn't feel nothing, baby, but I lied",
          'I almost cut a piece of myself, for your life',
          'Guess I was just another pit stop',
          "'Til you made up your mind",
          'You just wasted my time',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'You were on top, I put you on top',
          'I claimed you so proud, and openly, babe',
          'And when times were rough, when times were rough',
          'I made sure I held, you close, to me',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'So call out my name',
          'Call out my name when I kiss you so gently',
          'I want you to stay',
          "I want you to stay even though you don't want me",
          "Girl, why can't you wait",
          "Girl, why can't you wait 'til, I fall out of love",
          'Babe call out my name',
          "Girl, call out my name, and I'll be on my way",
          "And I'll be on my--",
        ],
      },
    ],
  },
  {
    number: 29,
    title: 'The Absyy',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I tried my best to not let you go',
          "I don't like the view",
          'From halfway down',
          "Just promise me that it won't be slow",
          'Will I feel the impact of the ground',
          "I tried to be something that I'll never be",
          'Why waste another precious hour',
          'Why waste another precious ounce',
          "I'd rather leave somewhat of a legacy",
          'Familiar',
          "A thought that's so familiar",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Let me close my eyes with dignity',
          "Let's end it all, the world's not far behind",
          "So what's the point of staying",
          "It's going up in flames, I know",
          'Yes, I know, ooh',
          'Oh-oh-oh',
          'Oh-oh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Just hold my heartbeat close to you',
          'Remember how it always beats for you',
          "I'm falling at the speed of light",
          "I'm staring at your shrinking face, don't cry",
          'You know my heart belongs to you',
          'One last time, say that you want me too',
          'The only words that gave me life',
          "Now I'll see you on the other side",
          'Oh-oh, oh-oh, oh-oh',
          'Oh-oh, oh-oh, oh-oh',
          'Oh-oh, oh-oh, oh-oh',
          'Oh-oh, oh-oh, oh-oh',
        ],
      },
    ],
  },
  {
    number: 30,
    title: 'Save Your Tears',
    sections: [
      {
        label: '-xo-',
        lines: [
          'I saw you dancing in a crowded room',
          "You look so happy when I'm not with you",
          'But then you saw me, caught you by surprise',
          'A single teardrop falling from your eye',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I don't know why I run away",
          "I'll make you cry when I run away",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "You could've asked me why I broke your heart",
          "You could've told me that you fell apart",
          "But you walked past me like I wasn't there",
          "And just pretended like you didn't care",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I don't know why I run away",
          "I'll make you cry when I run away",
          "Take me back 'cause I wanna stay",
          'Save your tears for another',
          'Save your tears for another day',
        ],
      },
    ],
  },
  {
    number: 31,
    title: 'Less Than Zero',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Remember I was your hero, yeah',
          "I'd wear your heart like a symbol",
          "I couldn't save you from my darkest truth of all",
          'I know',
          "I'll always be less than zero",
          'Oh yeah',
          'You tried your best with me, I know',
          "I couldn't face you with my darkest truth of all",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "'Cause I can't get it out of my head",
          "No, I can't shake this feeling that crawls in my bed",
          'I try to hide it but I know you know me',
          "I try to fight it but I'd rather be free",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Can we meet in the middle',
          "'Cause you were just like me before",
          "Now you'd rather leave me",
          'Than to watch me die in your arms',
          'Oh, oh',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I can't get it out of my head",
          "No, I can't shake this feeling that crawls in my bed",
          'I try to hide it but I know you know me',
          "I try to fight it but I'd rather be free",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'll always be less than zero",
          'You tried your best with me, I know',
        ],
      },
    ],
  },
  {
    number: 32,
    title: 'Blinding Lights',
    sections: [
      {
        label: '-xo-',
        lines: [
          "I've been tryna call",
          "I've been on my own for long enough",
          'Maybe you can show me how to love, maybe',
          "I'm going through withdrawals",
          "You don't even have to do too much",
          'You can turn me on with just a touch, baby',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I look around and',
          "Sin city's cold and empty",
          "No one's around to judge me",
          "I can't see clearly when you're gone",
          "I said ohhhh I'm blinded by the lights",
          "No I can't sleep until I feel your touch",
          "I said ohhhh I'm drowning in the night",
          "Oh when I'm like this you're the one I trust",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'm running out of time",
          "'Cause I can see the sun light up the sky",
          'So I hit the road in overdrive, baby',
          "Sin city's cold and empty",
          "No one's around to judge me",
          "I can't see clearly when you're gone",
          "I said ohhhh I'm blinded by the lights",
          "No I can't sleep until I feel your touch",
          "I said ohhhh I'm drowning in the night",
          "Oh when I'm like this you're the one I trust",
        ],
      },
      {
        label: '-xo-',
        lines: [
          "I'm just calling back to let you know",
          'I could never say this on the phone',
          'Will never let you go, this time',
          "I said ohhhh I'm blinded by the lights",
          "No I can't sleep until I feel your touch",
        ],
      },
    ],
  },
  {
    number: 33,
    title: 'Adaptation',
    sections: [
      {
        label: '-xo-',
        lines: [
          "When the sun comes up, you're searching for a love",
          "So your heart won't lead you to anyone",
          "When the sun goes down, I know what you become",
          "You become awake, unlike the rest of us"
        ],
      },
      {
        label: '-xo-',
        lines: [
          'I lay my head on a thousand beds',
          "It's been a test to see how far a man",
          "Can go without himself",
          "I think I lost the only piece that held it all in place",
          "Now my madness is the only love I let myself embrace",
          "I couldn've stayed"
        ],
      },
      {
        label: '-xo-',
        lines: [
          "But I chose the lie",
          "I chose the life",
          "Then I realized",
          "She might've been the one",
          "I let it go",
          "For a little fun",
          "I made a trade",
          "Gave away our days",
          "For a little fame",
          "Now I'll never see your face",
          "But it's okay, I adapted anyway"
        ],
      },
      {
        label: '-xo-',
        lines: [
          "Adapated to these models",
          "Who's adapted to the bottle",
          "They take it down like water",
          "Just to burn away their sorrows",
          "I'll stay up 'till tomorrow",
          "Just to tear down all their morals",
          "And all is fair in Love and War",
          "She's pure"
        ],
      },
    ],
  },
  {
    number: 34,
    title: 'House Of Balloons',
    sections: [
      {
        label: '-xo-',
        lines: ['Woah, Woah-oh-oh-oh-oh-oh-oh'],
      },
      {
        label: '-xo-',
        lines: [
          'Been on a further level since you came, no more pain',
          "You look into my eyes, you can't recognize my face",
          "You're in my world now, you can stay, you can stay",
          'But you belong to me, ooh, you belong to me',
          'If it hurts to breathe, open a window (Woo-ooh)',
          "Oh, your mind wants to leave (Yeah), but you can't go, oh",
        ],
      },
      {
        label: '-xo-',
        lines: [
          'This is a happy house',
          "We're happy here",
          'In a happy house',
          'Oh, this is fun',
        ],
      },
    ],
  },
  {
    number: 35,
    title: 'Moth To A Flame',
    sections: [
      {
        label: '-xo-',
        lines: [
          'Like a moth to a flame',
          "I'll pull you in, I pulled you back to",
          'What you need initially',
          "It's just one call away",
          "And you'll leave him, you're loyal to me",
          'But this time, I let you be',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "'Cause he seems like he's good for you",
          'And he makes you feel like you should',
          "And all your friends say he's the one",
          'His love for you is true',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'But does he know you call me when he sleeps',
          'But does he know the pictures that you keep',
          'But does he know the reasons why you cry',
          'Or tell me, does he know where your heart lies',
          'Where it truly lies',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Yeah, you should be with him, I let you go from time',
          'You should stay with him',
        ],
      },
      {
        label: '-xo-',
        lines: [
          "'Cause he seems like he's good for you",
          'And he makes you feel like you should',
          "And all your friends say he's the one",
          'His love for you is true',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'But does he know you call me when he sleeps',
          'But does he know the pictures that you keep',
          'But does he know the reasons why you cry',
          'Or tell me, does he know where your heart lies',
          'Where it truly lies',
        ],
      },
      {
        label: '-xo-',
        lines: [
          'Right here with me, babe',
          'Where it truly lies',
          'Where it truly lies',
          'Where it truly lies',
        ],
      },
    ],
  },
];
